class SearchCountry {
  final String name;

  SearchCountry({this.name});
}

List<SearchCountry> countries = <SearchCountry>[
  SearchCountry(name: "Bangladesh"),
  SearchCountry(name: "Bhutan"),
  SearchCountry(name: "Brunei Darussalam"),
  SearchCountry(name: "Cambodia"),
  SearchCountry(name: "China"),
  SearchCountry(name: "HongKong"),
  SearchCountry(name: "Indonesia"),
  SearchCountry(name: "Japan"),
  SearchCountry(name: "Republic of Korea"),
  SearchCountry(name: "Kyrgyzstan"),
  SearchCountry(name: "Laos"),
  SearchCountry(name: "Macao"),
  SearchCountry(name: "Malaysia"),
  SearchCountry(name: "Mongolia"),
  SearchCountry(name: "Myanmar"),
  SearchCountry(name: "Nepal"),
  SearchCountry(name: "Philippines"),
  SearchCountry(name: "Singapore"),
  SearchCountry(name: "SriLanka"),
  SearchCountry(name: "Taiwan"),
  SearchCountry(name: "Thailand"),
  SearchCountry(name: "VietNam"),
  SearchCountry(name: "Afganistan"),
  SearchCountry(name: "Azerbaijan"),
  SearchCountry(name: "Bahrain"),
  SearchCountry(name: "Egypt"),
  SearchCountry(name: "Georgia"),
  SearchCountry(name: "India"),
  SearchCountry(name: "Iran"),
  SearchCountry(name: "Iraq"),
  SearchCountry(name: "Israel"),
  SearchCountry(name: "Jordan"),
  SearchCountry(name: "Kazakhstan"),
  SearchCountry(name: "Kuwait"),
  SearchCountry(name: "Lebanon"),
  SearchCountry(name: "Oman"),
  SearchCountry(name: "Pakistan"),
  SearchCountry(name: "Qatar"),
  SearchCountry(name: "Russian Federation"),
  SearchCountry(name: "Saudi Arabia"),
  SearchCountry(name: "Turkey"),
  SearchCountry(name: "United Arab Emirates"),
  SearchCountry(name: "Argentina"),
  SearchCountry(name: "Bolivia"),
  SearchCountry(name: "Brazil"),
  SearchCountry(name: "Chile"),
  SearchCountry(name: "Colombia"),
  SearchCountry(name: "Ecuador"),
  SearchCountry(name: "Guatemala"),
  SearchCountry(name: "Mexico"),
  SearchCountry(name: "Panama"),
  SearchCountry(name: "Peru"),
  SearchCountry(name: "Puerto Rico"),
  SearchCountry(name: "Salvador"),
  SearchCountry(name: "Trinidad & Tobago"),
  SearchCountry(name: "Venezuela"),
  SearchCountry(name: "Canada"),
  SearchCountry(name: "United States"),
  SearchCountry(name: "Albania"),
  SearchCountry(name: "Andorra"),
  SearchCountry(name: "Austria"),
  SearchCountry(name: "Belgium"),
  SearchCountry(name: "Bosniaand Herzegovina"),
  SearchCountry(name: "Bulgaria"),
  SearchCountry(name: "Croatia"),
  SearchCountry(name: "Cyprus"),
  SearchCountry(name: "Czech Republic"),
  SearchCountry(name: "Denmark"),
  SearchCountry(name: "Estonia"),
  SearchCountry(name: "Finland"),
  SearchCountry(name: "France"),
  SearchCountry(name: "Germany"),
  SearchCountry(name: "Gibraltar"),
  SearchCountry(name: "Greece"),
  SearchCountry(name: "Hungary"),
  SearchCountry(name: "Iceland"),
  SearchCountry(name: "Ireland"),
  SearchCountry(name: "Italy"),
  SearchCountry(name: "Kosovo"),
  SearchCountry(name: "Lithuania"),
  SearchCountry(name: "Luxembourg"),
  SearchCountry(name: "Macedonia"),
  SearchCountry(name: "Malta"),
  SearchCountry(name: "Montenegro"),
  SearchCountry(name: "Netherlands"),
  SearchCountry(name: "Norway"),
  SearchCountry(name: "Poland"),
  SearchCountry(name: "Portugal"),
  SearchCountry(name: "Romania"),
  SearchCountry(name: "Serbia"),
  SearchCountry(name: "Slovakia"),
  SearchCountry(name: "Slovenia"),
  SearchCountry(name: "Spain"),
  SearchCountry(name: "Sweden"),
  SearchCountry(name: "Switzerland"),
  SearchCountry(name: "Ukraine"),
  SearchCountry(name: "United Kingdom"),
  SearchCountry(name: "Australia"),
  SearchCountry(name: "New Caledonia"),
  SearchCountry(name: "New Zealand"),
  SearchCountry(name: "Algeria"),
  SearchCountry(name: "Ghana"),
  SearchCountry(name: "Kenya"),
  SearchCountry(name: "Liberia"),
  SearchCountry(name: "Morocco"),
  SearchCountry(name: "Senegal"),
  SearchCountry(name: "South Africa"),
  SearchCountry(name: "Tanzania"),
  SearchCountry(name: "Tunisia"),
];
